import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import './../globals.css'
import SearchHeader from '../components/SearchHeader'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function SearchLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <SearchHeader />
      {children}
    </>
  )
}
